### ISSUE TITLE
Melhorias

### ISSUE THREAD

**Issue by kyriosdata** [NelsonWilliam/metodo#1]
Apesar da lista de referências estar disponível, não consegui localizar citações no texto. Não é suficiente colocar a bibliografia, é imprescindível, onde utilizado o conteúdo de uma fonte, indicar de onde este conteúdo é extraída.

**Comment by NelsonWilliam** [comment]
Foram adicionados indicadores numéricos ao longo do texto, indicando quais conteúdos foram extraídos das fontes.
